@apiPath = /api/v1
@host = http://localhost:4000

@apiUrl = {{host}}{{apiPath}}

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InN0cmluZyIsInVzZXJJZCI6MiwiaWF0IjoxNzUzMTExODM1LCJleHAiOjE3NTMxMTI0MzV9.GhePFZ8F08On9gSey5VydxE9r47zeQaipznaZBj67mQ

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InN0cmluZyIsInVzZXJJZCI6MiwiaWF0IjoxNzUzMTExODM1LCJleHAiOjE3NTM3MTY2MzV9.uICytcOG66UeSaSmOsptORCd-mwUbYFsNCwgifkZ7-g

### Health Check
GET {{apiUrl}}/healthcheck

### Register
POST {{apiUrl}}/auth/register
Content-Type: application/json

{
    "name": "Caio Brito",
    "age": 19,
    "email": "caio@mail.com",
    "password": "12345"
}

### Login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "string"
}

### Refresh Access Token
POST {{apiUrl}}/auth/refresh-access-token
Cookie: refreshToken={{refreshToken}}
Content-Type: application/json

### Enable 2FA
POST {{apiUrl}}/auth/2fa/enable
Authorization: Bearer {{accessToken}}
Content-Type: image/png

### Verify 2FA
POST {{apiUrl}}/auth/2fa/verify
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "code": "880985"
}

### Task List
GET {{apiUrl}}/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Task Creation
POST {{apiUrl}}/task
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "My first task",
    "description": "",
    "dueDate": "2025-11-21",
    "isDone": true
}

### Task Update

### Task Partial Update (change status)

### Task Deletion 