@apiPath = /api/v1
@host = http://localhost:4000

@apiUrl = {{host}}{{apiPath}}

### === API STATUS === ###

### Health Check
GET {{apiUrl}}/healthcheck

### === AUTH ENDPOINTS === ###

### Register
POST {{apiUrl}}/auth/register
Content-Type: application/json

{
    "name": "Vitor Muraoka",
    "age": 18,
    "email": "vitor.muraoka2@developz.com.br",
    "password": "vitor123"
}

### Login
# @name auth
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
    "email": "caio@mail.com",
    "password": "12345"
}

###

@accessToken = {{auth.response.body.accessToken}}
@authToken = {{auth.response.body.authToken}}

### Verify 2FA (login proccess)
# @name 2fa
POST {{apiUrl}}/auth/2fa/verify
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "code": "315160"
}

###

@accessToken = {{2fa.response.body.accessToken}}

### Refresh Access Token
# @name refresh
POST {{apiUrl}}/auth/refresh-access-token

###

@accessToken = {{refresh.response.body.newAccessToken}}

### Enable 2FA
POST {{apiUrl}}/auth/2fa/enable
Authorization: Bearer {{accessToken}}
Content-Type: image/png

### Verify 2FA (setup proccess - while enabling)
POST {{apiUrl}}/auth/2fa/setup/verify
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "code": "029785"
}

### === TASK ENDPOINTS === ###

### Task List
GET {{apiUrl}}/task
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Specific Task
GET {{apiUrl}}/task/12
Authorization: Bearer {{accessToken}}

### Task Creation
POST {{apiUrl}}/task
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "This task is insane!",
    "description": "LOOK AT MY NEW TASK. LET'S GO!!!",
    "dueDate": "2021-05-11"
}

### Task Update
PUT {{apiUrl}}/task/12
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "Now, it's not"
}

### Task Partial Update (change status)
PATCH {{apiUrl}}/task/13
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "isDone": true
}

### Task Deletion 
DELETE {{apiUrl}}/task/12
Authorization: Bearer {{accessToken}}

### === USER ENDPOINTS === ###

### User Data (for logged user)
GET {{apiUrl}}/user
Authorization: Bearer {{accessToken}}