@apiPath = /api/v1
@host = http://localhost:4000

@apiUrl = {{host}}{{apiPath}}

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkNhaW8gQnJpdG8iLCJ1c2VySWQiOjQsImlhdCI6MTc1MzExOTgyOSwiZXhwIjoxNzUzMTIwNDI5fQ.w6L3eRtjEhAzCzDppJgOzi4zD5V5h3wY6ttP-plMLh8

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkNhaW8gQnJpdG8iLCJ1c2VySWQiOjQsImlhdCI6MTc1MzExOTgyOSwiZXhwIjoxNzUzNzI0NjI5fQ.D0DfjBlLzIcfyhzwtUlqqiSUMjNfWqxLvEcv-q0MNb4

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkNhaW8gQnJpdG8iLCJ1c2VySWQiOjQsImlhdCI6MTc1MzExODkzOCwiZXhwIjoxNzUzMTIyNTM4fQ.OBz7YvTudrZQd_Ii3JPvrTuCy0TimoJ8InIB5dgtDug

### Health Check
GET {{apiUrl}}/healthcheck

### Register
POST {{apiUrl}}/auth/register
Content-Type: application/json

{
    "name": "Caio Brito",
    "age": 19,
    "email": "caio1@mail.com",
    "password": "12345"
}

### Login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
    "email": "caio1@mail.com",
    "password": "12345"
}

### Verify 2FA (login proccess)
POST {{apiUrl}}/auth/2fa/verify
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "code": "997492"
}

### Refresh Access Token
POST {{apiUrl}}/auth/refresh-access-token
Cookie: refreshToken={{refreshToken}}
Content-Type: application/json

### Enable 2FA
POST {{apiUrl}}/auth/2fa/enable
Authorization: Bearer {{accessToken}}
Content-Type: image/png

### Verify 2FA (setup proccess - while enabling)
POST {{apiUrl}}/auth/2fa/setup/verify
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "code": "113953"
}

### Task List
GET {{apiUrl}}/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### Task Creation
POST {{apiUrl}}/task
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "Other task",
    "description": "Testing the description 123",
    "dueDate": "2025-11-21"
}

### Task Update

### Task Partial Update (change status)

### Task Deletion 