openapi: 3.1.0
info:
  title: Task Management API
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/v1
    description: Local development
  - url: https://api.yoursite.com/api/v1
    description: Production
paths:
  /auth/register:
    post:
      summary: Let you register in the App
      description: This route creates a new user.
      operationId: registerUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
        '409':
          description: The App already has a user with the email provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: The email provided is already in use.
        '422':
          description: Your request does not follow the body pattern or some field does not follow some constraint.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error. If it persists, contact the admin.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
  /auth/login:
    post:
      summary: Let you login in the App
      description: This route checks the credentials and logs the user into App.
      operationId: loginUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticateUserRequest'
      responses:
        '200':
          description: User successfully passed into authentication!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticateUserResponse'
        '401':
          description: Invalid credentials (email and/or password).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Invalid credentials.
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: User not found.
        '422':
          description: Your request does not follow the body pattern or some field does not follow some constraint.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error. If it persists, contact the admin.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
  /auth/refresh-access-token:
    post:
      summary: Refresh access token
      description: |
        Generates a new access token using a valid refresh token provided via cookie named `refreshToken`.
      tags:
        - Auth
      parameters:
        - in: cookie
          name: refreshToken
          required: true
          schema:
            type: string
          description: Refresh token required in cookie
      responses:
        '200':
          description: New access token generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  newAccessToken:
                    type: string
                    description: JWT access token for authenticated endpoints
        '400':
          description: Refresh token is missing from the cookies (refreshToken missing (cookie))
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: refreshToken missing (cookie)
        '401':
          description: |
            Refresh token is expired, invalid, malformed, or not yet active. Examples: 
              - Refresh token expired (TokenExpiredError) 
              - Invalid refresh token or malformed request (JsonWebTokenError) 
              - Refresh token is not yet active (NotBeforeError)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                TokenExpiredError:
                  value:
                    message: Refresh token expired
                JsonWebTokenError:
                  value:
                    message: Invalid refresh token or malformed request.
                NotBeforeError:
                  value:
                    message: Refresh token is not yet active
        '500':
          description: Unexpected authentication error (An unexpected authentication error occurred.)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error
  /auth/2fa/enable:
    post:
      summary: Generate 2FA QR Code for logged user
      description: |
        Returns a PNG image with a QR code for 2FA setup.  
        Requires authentication (JWT Bearer Token).
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: QR code image generated successfully
          content:
            image/png:
              schema:
                type: string
                format: binary
        '409':
          description: 2FA is already enabled for this user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: 2FA is already active.
        '500':
          description: Failed to generate QR code or unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
  /auth/2fa/setup/verify:
    post:
      summary: Validate 2FA code during setup
      description: |
        Confirms the 2FA setup by validating the code sent by the user.  
        Requires authentication (JWT Bearer Token).
      tags:
        - Auth
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultipleFactorAuthDto'
      responses:
        '204':
          description: Valid code. 2FA enabled successfully.
        '400':
          description: Invalid 2FA code.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Invalid 2FA code.
        '404':
          description: 2FA secret not found for user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: 2FA secret not found.
        '422':
          description: Invalid request payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
  /auth/2fa/verify:
    post:
      summary: Authenticate user via 2FA after login
      description: |
        Receives a 2FA code, validates it, and returns accessToken in response and refreshToken as a cookie.  
        The user must already be partially authenticated (temporary auth token).
      tags:
        - Auth
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultipleFactorAuthDto'
      responses:
        '200':
          description: 2FA authentication successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: JWT to use for authenticated endpoints
        '400':
          description: Invalid 2FA code.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Invalid 2FA code.
        '404':
          description: 2FA secret not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: 2FA secret not found.
        '422':
          description: Invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
  /task:
    get:
      summary: Get all tasks for the authenticated user
      tags:
        - Task
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of the user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new task
      tags:
        - Task
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTask'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '422':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /task/{taskId}:
    get:
      summary: Get a task by its ID (for authenticated user)
      tags:
        - Task
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
          description: Task ID
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid taskId parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update all properties of a task
      tags:
        - Task
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTask'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '422':
          description: Invalid parameters or request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    patch:
      summary: Update only the status (isDone) of a task
      tags:
        - Task
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeTaskStatus'
      responses:
        '204':
          description: Task status updated successfully
        '422':
          description: Invalid parameter or body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a task
      tags:
        - Task
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Task deleted
        '400':
          description: Invalid taskId parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /user:
    get:
      summary: Get logged user information
      description: Returns the profile information of the authenticated user.
      operationId: getUserProfile
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: User not found.
        '500':
          description: Internal server error. If it persists, contact the admin.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
          description: User name (required)
        age:
          type: number
          minimum: 1
          description: User age (required)
        email:
          type: string
          maxLength: 255
          format: email
          description: User email (required)
        password:
          type: string
          description: User password (required)
        2faEnabled:
          type: boolean
          default: false
          description: If the user want 2faEnabled (optional, default=false)
      required:
        - name
        - age
        - email
        - password
    CreateUserResponse:
      type: object
      properties:
        userId:
          type: string
          description: User ID
        userName:
          type: string
          description: User name
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Human-readable error message describing the problem
        code:
          type: string
          description: Application-specific error code (optional)
        details:
          type: object
          description: Additional error details (optional, can include validation field errors)
          additionalProperties: true
      required:
        - message
    AuthenticateUserRequest:
      type: object
      properties:
        email:
          type: string
          maxLength: 255
          format: email
          description: User email (required)
        password:
          type: string
          description: User password (required)
      required:
        - email
        - password
    AuthenticateUserResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT access token to use when accessing endpoints
    MultipleFactorAuthDto:
      type: object
      properties:
        code:
          type: string
          description: 6-digit code sent by the user
          minLength: 6
          maxLength: 6
      required:
        - code
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
          nullable: true
        dueDate:
          type: string
          format: date
          nullable: true
        isDone:
          type: boolean
        owner:
          type: integer
    CreateTask:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        dueDate:
          type: string
          format: date
        isDone:
          type: boolean
          default: false
      required:
        - title
    UpdateTask:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        dueDate:
          type: string
          format: date
        isDone:
          type: boolean
        owner:
          type: integer
    ChangeTaskStatus:
      type: object
      properties:
        isDone:
          type: boolean
      required:
        - isDone
    User:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        email:
          type: string
        2faEnabled:
          type: boolean
