openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/v1
    description: Local development
  - url: https://api.seusite.com/api/v1
    description: Production
paths:
  /auth/register:
    post:
      summary: Let you register in the App
      responses:
        '201':
          description: User data
          content:
            application/json:
              schemas:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: number
        owner:
          type: number
        title:
          type: string
        description:
          type: string
        dueDate:
          type: date
        isDone:
          type: boolean
    User:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        email:
          type: string
        2faEnabled:
          type: boolean
