openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/v1
    description: Local development
  - url: https://api.seusite.com/api/v1
    description: Production
paths:
  /auth/register:
    post:
      summary: Let you register in the App
      description: This route creates a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schemas:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: number
        owner:
          type: number
        title:
          type: string
        description:
          type: string
        dueDate:
          type: date
        isDone:
          type: boolean
    User:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        email:
          type: string
        2faEnabled:
          type: boolean
    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
          description: User name (required)
        age:
          type: number
          minimum: 1
          description: User age (required)
        email:
          type: string
          maxLength: 255
          format: email
          description: User email (required)
        password:
          type: string
          description: User password (required)
        2faEnabled:
          type: boolean
          default: false
          description: If the user want 2faEnabled (optional, default=false)
        required:
          - name
          - age
          - email
          - password
