openapi: 3.1.0
info:
  title: Task Management API
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/v1
    description: Local development
  - url: https://api.seusite.com/api/v1
    description: Production
paths:
  /auth/register:
    $ref: "./paths/auth.register.yaml"
  /auth/login:
    $ref: "./paths/auth.login.yaml"
  /auth/refresh-access-token:
    $ref: "./paths/auth.refreshAccessToken.yaml"

