name: Continuous Integration Pipeline (CI) # Workflow Name => Pipeline CI
on:
  pull_request: # The Event
    branches: ["main"] # The Conditions
jobs:
  continuous-int:
    runs-on: self-hosted # The OS (Linux Debian, instancia-developz)
    environment: CI Workflow # The Environment of Git Hub in Which my Secrets Will be Get From
    steps:
      - name: Node.js Setup # The Environment Dependencies (name)
        uses: actions/setup-node@v2 # The Environment Dependencies (action -> set of commands to setup the dependency)
        with: # The Environment Dependencies (arguments -> to run with the commands)
          node-version: 22.
      - name: Pull the Base Code # The Code Base (name)
        uses: actions/checkout@v3 # The Code Base (set of commands)
      - name: Install Dependencies and Build # The Commands [my set of commands (project-based), not third-party commands, like "actions/..."]
        run:
          | # Because it's my commands, I'll not use "uses". Instead, I'll use "run". "|" is a YAML convention for multiline
          npm install
          npm run build
      - name: Setup .env file
        run: |
          rm -f .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "POSTGRES_VERSION_TAG=${{ secrets.POSTGRES_VERSION_TAG }}" >> .env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
          echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "REDIRECT_PATH=${{ secrets.REDIRECT_PATH }}" >> .env
          echo "BASE_API_PATH=${{ secrets.BASE_API_PATH }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DB_RETRY_DELAY_MS=${{ secrets.DB_RETRY_DELAY_MS }}" >> .env
          echo "DB_RETRY_ATTEMPTS=${{ secrets.DB_RETRY_ATTEMPTS }}" >> .env
      - name: Unit Tests & Integration Tests
        run: npm test
